### PR TITLE
Broken links

### LINKED ISSUE #7: Custom CSS style sheet request returns 404 in production
The current [static file path to our custom CSS sheet](https://github.com/seattleflu/scan-switchboard/blob/d1912057a705a38820dab85ceb89ae715f2fa693/datasette.yaml#L34) is found locally but results in a 404 on production: 
image

The custom CSS doesn't do much right now -- it just hides the custom SQL query visible at /scan-redcap, so this isn't a high priority issue. 

To solve this problem, either stop using absolute URL for the custom CSS sheet, or hard code its path to the production URL.

### PR DESCRIPTION
**Pull request by tsibley**
Details in commit messages. Resolves #7 and #8, because #8 finally got on my nerves enough when I wanted to go look at some numbers.

### CODE REVIEW

File: static/fix-links.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+   *   -trs, 2 July 2020
+   */
+  if (document.location.origin !== production_base_url.origin) {
+    console.debug(`fix-links: skipping page; origin ${document.location.origin} is not ${production_base_url.origin}`)
+    return;
+  }
+
+  const broken_link = url =>
+       url.origin !== production_base_url.origin
+    && url.origin.match(/localhost|127[.]0[.]0[.]1/);
```
Comment (kairstenfay) [inline static/fix-links.js:20]: I'm curious, why do you use square brackets here to "escape" the `.` instead of using a backslash? e.g. `127\.0\.0\.1`

Comment (tsibley) [reply static/fix-links.js:20]: Good question! No particular reason. I started using `[.]` in the last year or so in situations where backslashes are annoying to escape, and it's bled over into more general situations since then.

**Comment by tsibley** [comment]
Always good to look at warnings. That particular one for `/switchboard/static/fix-links.js` is expected in dev. In production, the expected warning will be for `/static/fix-links.js`. Rationale is in 4342a46 (which is for our CSS, but it applies the same to the JS).

**Comment by kairstenfay** [comment]
> Always good to look at warnings. That particular one for `/switchboard/static/fix-links.js` is expected in dev. In production, the expected warning will be for `/static/fix-links.js`. Rationale is in [4342a46](https://github.com/seattleflu/scan-switchboard/commit/4342a46743ed5f3363e7b6308c0a714c1c8db04e) (which is for our CSS, but it applies the same to the JS).

That makes sense. Thanks!

**Comment by tsibley** [comment]
Hit a bug after deployment which I fixed in https://github.com/seattleflu/scan-switchboard/commit/ed7b02623d19f6b41ad7fb766b2bdb736a7b8cb6.
